Repository CSbyUs/csbyus-on-rails, pull requests merged in 2019-03, with the labels that each got.

#45 Centering team card text, linking to individual bios!
  Gemfile
  Gemfile.lock
  app/javascript/components/App.js
  app/javascript/components/InfoSegment.js
Labels: enhancement

#51 Eliza mainui
  .gitignore
  app/javascript/components/IndividualBiosPage.js
Labels: bug

#49 SearchBar partially implemented
  app/assets/data/coursesInfo.js
  app/assets/javascripts/jss/components/courseOverviewComponentStyles.js
  app/javascript/components/CourseOverview.js
  app/javascript/components/SearchBar.js
Labels: enhancement, help wanted

#59 New images for our impact and about us
  app/assets/javascripts/jss/components/contactFormComponentStyles.js
  app/javascript/components/AboutLogo.js
  app/javascript/components/ContactForm.js
  app/javascript/components/Footer.js
  app/javascript/components/HeaderAppBar.js
  app/javascript/components/Home.js
Labels: enhancement

#60 Header app bar responsive design and blog improvements
  app/assets/data/blogPosts.js
  app/assets/data/coursesInfo.js
  app/assets/data/posts/blog-post.0.js
  app/assets/data/posts/blog-post.1.js
  app/assets/javascripts/jss/components/headerComponentStyles.js
  app/assets/javascripts/jss/components/homeComponentStyles.js
  app/javascript/components/Blog.js
  app/javascript/components/HeaderAppBar.js
  app/javascript/components/InTheNews.js
  app/javascript/components/Post.js
  app/javascript/components/PostCard.js
Labels: enhancement
